### ISSUE TITLE
Simplest execution of simulator

### ISSUE THREAD

**Issue by hansyuan** [EMSTrack/Algorithms#14]
# Crossing our T's and Dotting out I's

#### Reducing the cognitive overload of using the simulator and making it presentable in the paper
- using a **driver**: 
  - Settings: using Yaml?
  - requirements.txt/setup.py
  -  Looking at the possible ways to interface the simulator (or interface the interface) 
- Reorganizing the **coordinates**
  - From hardcoded in the python file to storing them inside yaml files

**Comment by hansyuan** [comment]
(Trying to see how well this Github thing works)

One thought about testing the simulator. Since randomness is part of a lot of major parts, how do we test it lol. We can provide seeds, and one approach based on using seeds requires knowing how often the random methods are called

**Comment by hansyuan** [comment]
# winter2019 branch

### We want to move a lot of the functionality from main.py to ems/driver.py 

#### Currently working on user input. 

-

**Comment by hansyuan** [comment]
- Need to test the installation instructions in the README.md (install a v-env...)
- yaml can be used with the sim now, but I need to update the CLI and stuff

**Comment by hansyuan** [comment]
Useful towards sharing the simulator with other people and having it be something we present in a paper: 

1) The simplest YAML config possible. Hypothetically, all algorithms and data will choose random generation or constant. 
2) The simplest data files possible. We use the more realistic algorithms, but the data from which we read will be simplest. For example, a `bases.csv` where there are two bases.

**Comment by hansyuan** [comment]
sys.argv (argparse) in the main

**Comment by hansyuan** [comment]
TODO 

- Scientifically create the polygon
- Scientifically create the example bases.csv, etc files

**Comment by hansyuan** [comment]
- Move forward the command line parsing
- Parallelizing the times generator

**Comment by hansyuan** [comment]
Pro of keeping Hospitals - shows the simulated ambulance can go to more than one location 
Con - Complexity (?) 
Cost - Larger yaml file? 

Is there anything else for the above three things? It might not be useful to have the ambulance travel to hospitals but it might be good to show for first time viewers?

**Comment by hansyuan** [comment]
Deciding whether the ambulance going to the hospital is something we'd want to simulate, probably based on the AT_INCIDENT event. The user can maybe pull some levers to change the way Events happen, but they probably shouldn't specify the events directly. 

It's more work to change something under the hood right now. In the future we can think about making ambulance trips more realistic. For now it seems okay to iterate a list of events even if it has 6 types of events rather than 4. The implementation complexity won't improve that much from removing one type of event and the print statements are confusing at first regardless. The solution there would be to run 1 or 2 cases instead.

**Comment by thl024** [comment]
Okay in that case, I believe the minimal example is finished. It's called minimal.yaml in the winter2019 branch. It's still a little lengthy imo but everything is pretty much random except I've hardcoded hospitals.

I'm going to attempt visualizing them so we can get something for the paper.

**Comment by hansyuan** [comment]
@thl024 We can resolve and unpin this issue if this is done
