### ISSUE TITLE
Differentiate object tags and string primitives in yaml parsing

### ISSUE THREAD

**Issue by thl024** [EMSTrack/Algorithms#24]
Currently, the Driver is unable to tell the difference between object tags and string primitives. In the event that an object tag is named exactly the same as a string primitive, the driver will always populate the parameter with the object. 

We can differentiate between the two by enforcing some notation in the yaml that identifies a class form a string (like in html with the pound sign or something)

**Comment by hansyuan** [comment]
Optional k: v where the class is specified explicitly?

**Comment by thl024** [comment]
I was thinking we do something similar to HTML: e.g.

Instead of: 
`travel_times: tt`

We have:
`travel_times: #tt` or `travel_times: .tt`

To reference an object.

**Comment by hansyuan** [comment]
what happens currently? What's the order of operations if the class exists?

**Comment by thl024** [comment]
Always creates the class

**Comment by thl024** [comment]
#26
