### ISSUE TITLE
Data format -- want headers? Format of the bases?

### ISSUE THREAD

**Issue by hansyuan** [EMSTrack/Algorithms#28]
We agree with CSV, but there are a few details to make sure: 

- Should we use headers in the CSV or no? What are the pros and cons? 

- The bases files are a list but include many strings not used by the simulator. Namely, they are: 

`'id','name','type','vics',`

**Comment by hansyuan** [comment]
I personally like headers as they are explicit denotations of what each column is. It can also open the door to a more kwargs style format than a positional args style -- less rigid formats.

**Comment by thl024** [comment]
I agree that headers should be required. So we should modify the CSVs and code to include headers?

**Comment by hansyuan** [comment]
Yes, let's do it
