### ISSUE TITLE
DurationGenerator

### ISSUE THREAD

**Issue by hansyuan** [EMSTrack/Algorithms#50]
LEAVE THIS FOR LATER:

How is the Duration Generator implemented? Is it identical to the script where a random set of size n points is created and then n^2 travel times are generated to produce the CruzRoja structured times? Or is it generating on the fly, which takes out the use case of the kd-tree? If it generates on the fly, is it storing the times for amortization?

**Comment by thl024** [comment]
Discussed on slack. Generated on the fly, taking out the kd-tree. The sim is implemented such that no matter how travel times are generated, they'll be stored and written to file.
