### ISSUE TITLE
Simulator Output - Save the outputs in some format (yaml or python dump)

### ISSUE THREAD

**Issue by hansyuan** [EMSTrack/Algorithms#9]
- The output of the simulator should be made optional to avoid printing overhead

**Comment by thl024** [comment]
@hansyuan Maybe [loggers](https://docs.python.org/3/library/logging.html)?

Library has support for logging to an output file.

**Comment by hansyuan** [comment]
@thl024 Already implemented as the debug flag in the yaml file. The flag gets passed in and all the print statements are now `if debug: print` statements
